In [2]:
import numpy as np

In [4]:
x = np.arange(1, 13, 1).reshape(3, 4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
x[1:2, 2]

array([7])

In [16]:
x[[0, 2], 2]

array([ 3, 11])

In [17]:
x[[0, 2], :2]

array([[ 1,  2],
       [ 9, 10]])

In [18]:
x[0, 1]

2